### ISSUE TITLE
MODE_GC16 cannot show grayscales' color normally.

### ISSUE THREAD

**Issue by lanistor** [martinberlin/lv_port_esp32-epaper#9]
Thanks for supply such an amazing library, really.

------

The grayscales' color cannot perform normally, had set `enum EpdDrawMode updateMode = MODE_GC16`.

Here is the demo:
### using lv_port_esp32-epaper
> The background color in the left side is set as `#dddddd`;

![lv_port_esp32-epaper](https://github.com/lanistor/assets/blob/master/epaper/lvgl_epdiy.jpg?raw=true)

### epdiy' demo
![epdiy](https://github.com/lanistor/assets/blob/master/epaper/epaper.jpg?raw=true)

Here are these problems:
1. Grayscales' color: `#dddddd` (the background color in the left side) seem to be `#666666`, and `#eeeeee` even cannot be show.
2. The font has serious burrs, which epdiy hasnot.
3. The render is really slow, nearly need 10 seconds to render the left-side-background, while epdiy's demo can render fullscreen in nearly one second.

So, why? Is the algorithmic problems with color mapping? And is there a possible way to resolve it?

Thanks very much.

**Comment by martinberlin** [comment]
Hi Lanistor, 
sorry I saw this quite late. I think at this point we advanced significantly in rendering times with epdiy v7 and your own improvements. 

Please keep it open in case we need to discuss something more here otherwise you can close it.

**Comment by martinberlin** [comment]
Closing here since it seems old and by this point you would have figured out this one!

**Comment by lanistor** [comment]
> Closing here since it seems old and by this point you would have figured out this one!

OK. sorry forgot to close it.
